spring.application.name=aqi-search-engine

# AQICN Configuration

aqi.api.base-url=https://api.waqi.info
aqi.api.token=YOUR_TOKEN

# Cache
spring.cache.type=caffeine

# Server
server.port=8080

# Logging
logging.level.com.shivakumar.aqi=DEBUG