spring.application.name=aqi-search-engine

# AQICN Configuration

aqi.api.base-url=https://api.waqi.info
aqi.api.token=97597801497743538206766cfe752c835c4961b0

# Cache
spring.cache.type=caffeine

# Server
server.port=8080

# Logging
logging.level.com.shivakumar.aqi=DEBUG